[phases.setup]
aptPkgs = ["chromium", "chromium-driver", "fonts-freefont-ttf", "libatk-bridge2.0-0", "libgtk-3-0", "libnss3", "libxss1", "libasound2", "xvfb"]

[phases.build]
cmds = ["which chromium || which chromium-browser || find / -name 'chrom*' -type f 2>/dev/null | head -5"]
